server:
  port: 8888
  

# CONFIGURACION CON GIT
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lascencion23/admin-config-data.git
          default-label: main
          clone-on-start: true
          force-pull: true
      discovery:
        enabled: false  

#  cloud:
#    config:
#        server:
#          native:
#            search-locations: file:///C:\Ambiente-desarrollo\dockerizar\admin-config-data
#  profiles:
#    active: native    

  



# EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
